### ISSUE TITLE
Intended change of object tree entries?

### ISSUE THREAD

**Issue by studio1gmbh-pimcore** [BlackbitDigitalCommerce/pimcore-data-director#165] opened 2024-05-14 17:33 UTC
@janwalther @BlackbitDevs

Hi there, 

since commit `fbff4a8`, there is an issue with the object tree.

**Details:**
- The first localized field of type "input" is now displayed in the tree, with the object key in parentheses.
- This change was introduced with a commit message stating "bugfixes," but no further documentation or notes are available in the changelog.
- The change was implemented in `getElementText` of `lib/Pim/AdminStyle/GridViewFieldsAdminStyle.php`
- Example: 
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/125017857/7e138471-2c9f-43d6-9f8a-4080e1cd572f)

**Questions:**
- Was this change intentional or an unintended side effect?
- If it is a feature, can it be made optional? Users are experiencing confusion due to this change.

Thank you for your assistance.

/JKO

**Comment by BlackbitDevs** [comment] 2024-05-15 06:33
Actually it was intended - but obviously it is not implemented in a good way. Nor documented...

The goal was to make the element keys translatable - because a lot of clients face the challenge that they have to decide which language to use for folder names and object keys. Pimcore does not offer any mechanism to translate those keys.
So it is checked if the current user uses a different language than the configured system default language. If this is the case, then the first localized field gets used as the object key.

But I agree that using the first localized field was a wrong decision. I have now changed it so that the element key is tried to be translated via Pimcore's admin translations. Then initially nothing will change as the translation does not exist yet - but if you want, you can translate the element keys this way.
WDYT about that, @studio1gmbh-pimcore ?

The change is released in 3.6.29

**Comment by studio1gmbh-pimcore** [comment] 2024-05-15 09:28
@BlackbitDevs Thank you for the clarification. We also think, that the approach of making the key translatable would be very useful!

**Comment by studio1gmbh-pimcore** [comment] 2024-05-15 09:33
@BlackbitDevs Thank you for the clarification. We also think, that the approach of making the key translatable would be very useful!

However, we still have some suggestions, we think it's worth to think about:

1. It would make sense, that the tab title of the opened object will be translated too
2. Can the feature be extended also for assets and documents?
3. It would be usefull to mention this feature in the documentation, to prevent confusion :)

/JKO

**Comment by BlackbitDevs** [comment] 2024-05-15 13:36
> 1. It would make sense, that the tab title of the opened object will be translated too

Currently this is not possible with Pimcore's built-in features, there the real `object key` gets used, see https://github.com/pimcore/admin-ui-classic-bundle/blob/558c7c245208793ed67a413eca86810d75fcb325/public/js/pimcore/object/object.js#L217

But maybe I could use the `postOpenObject` event... yes, this is possible. I have just implemented it for 3.7...

> 2. Can the feature be extended also for assets and documents?

Yes, this should already work in 3.6.29

> 3. It would be usefull to mention this feature in the documentation, to prevent confusion :)

Have updated it today morning (but for now only in 3.7 branch). But you can also see it in https://www.blackbit.de/Blackbit/1.pimcore/Handbücher/Pimcore-Data-Director-Manual.pdf

> ## Translatable element names in element tree
> 
> By default Pimcore does not support translating element names. This leads to the problem that you have to decide which language to use for folder names and object keys. This complicates understanding the system for foreign language data maintainers.
> 
> Data Director includes this feature (for Pimcore >= 11). If the user's language differs from the configured system default language, the element keys are tried to be translated via admin translations. Initially they will not exist, so the displayed element names will stay the same. But this way you can translate folder names or object keys if you want to. The element name gets used as translation key, so you can go to admin translations, search for the element key and then translate it in the desired language.

**Comment by studio1gmbh-pimcore** [comment] 2024-05-16 06:41
@BlackbitDevs Thanks a lot, good job! :)

**Closed** 2024-05-16 06:41 UTC
