### ISSUE TITLE
Could not instantiate ""

### ISSUE THREAD

**Issue by betterapp** [BlackbitDigitalCommerce/pimcore-data-director#99] opened 2023-05-31 10:20 UTC
We have such error message
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/3050cf61-a670-4adb-b714-05575bef16a1)

when try to set Row Data Field for Export DataPort

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/28612930-b82b-40a8-b7d1-b931c4b5a0e0)

![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/3e16cefa-4a44-428d-9ca3-511719f6b788)

For 
![image](https://github.com/BlackbitDigitalCommerce/pimcore-data-director/assets/7449124/4652a96b-5c38-43cd-99d3-548619010082)
which is not Advanced relation everything is ok.

DD: 3.2.22

**Comment by BlackbitDevs** [comment] 2023-05-31 11:34
I cannot reproduce this error currently. Can you please click "Details" (preferably with `APP_DEBUG=true`) to see the call stack?

**Comment by betterapp** [comment] 2023-05-31 11:39
in /home/daniel/Web/pimcore/vendor/blackbit/data-director/lib/Pim/Item/ItemMoldBuilder.php:123
#0 /home/daniel/Web/pimcore/vendor/blackbit/data-director/Controller/ImportconfigController.php(2223): Blackbit\DataDirectorBundle\lib\Pim\Item\ItemMoldBuilder->getItemMoldByClassname()
#1 /home/daniel/Web/pimcore/vendor/blackbit/data-director/Controller/ImportconfigController.php(2370): Blackbit\DataDirectorBundle\Controller\ImportconfigController->getDataQueryTargetClass()
#2 /home/daniel/Web/pimcore/vendor/blackbit/data-director/Controller/ImportconfigController.php(1888): Blackbit\DataDirectorBundle\Controller\ImportconfigController->getDataQueryTargetClass()
#3 /home/daniel/Web/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Blackbit\DataDirectorBundle\Controller\ImportconfigController->getDataQuerySelectorItems()
#4 /home/daniel/Web/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw()
#5 /home/daniel/Web/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle()
#6 /home/daniel/Web/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle()
#7 {main}

**Comment by BlackbitDevs** [comment] 2023-05-31 11:56
This error got fixed in 3.4 (used wrong array key and thus it was tried to create a class from an empty class name).
Have now also fixed this in 3.3.17.

**Closed by BlackbitDevs** 2023-05-31 11:56 UTC

**Comment by BlackbitDevs** [comment] 2023-05-31 12:02
I backported it to 3.2.39.

**Comment by betterapp** [comment] 2023-05-31 12:03
Thank You
